sudo: false
language: scala
dist: trusty
scala:
  - "2.12.6"
script:
  - sbt clean coverage coreJVM/test coverageReport
after_success:
  - pip install --user codecov && codecov
branches:
  only:
    - master
cache:
  directories:
    $HOME/.ivy2/cache
jdk:
  - openjdk8
